### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [TheTermos/mobkit#30]
I started looking into adding spawning to paleotest, which uses mobkit and noticed how complex spawning is compared to mobs redo, which I am familiar with. I've looked at examples from wildlife and water_life and it seems very complex to implement. Is there a simpler way or plans to make spawning simpler?

**Comment by TheTermos** [comment]
Yes, there's this function available `mobkit.get_spawn_pos_abr()`
The examples don't use the function, because they predate it.

Still isn't going to be as simple as redo, because it just uses ABMs which are - pros: trivial to implement, cons: works horribly.

**Comment by TheTermos** [comment]
Hope that answers the question, closing.

**Comment by HeyITGuyFixIt** [comment]
That is useful. Come to find out, mob_core has the functions I was looking for.
