### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by ghost** [TheTermos/mobkit#34]
Call to deprecated function 'get_player_velocity', please use 'get_velocity'
- init.lua:233

**Comment by TheTermos** [comment]
Yes I'm aware of that. 
It's too soon to stop using get_player_velocity because get_velocity doesn't work with 5.3.
Best I can do is to file an issue with MT to bring down the spam.

**Comment by ghost** [comment]
oh ok, thanks

**Comment by TheTermos** [comment]
It seems that the message is being issued only once per server run, so maybe filing an issue isn't worth it.
Do you agree?

**Comment by ghost** [comment]
yes, allright
